chore: Update btrfs-progs to 6.14-1deepin1
Follow changes:
 *1. Update source to 6.14-1 from Debian.
  2. Reapply commit 7fb3f34 ("Fix: not scan if no btrfs in initramfs
to improve boot performance") and commit b40cf5f ("Fix: fix commit
7fb3f3488b6b480215b76862e3e878bdc23f79c7") from xinpeng wang.

Link: http://deb.debian.org/debian/pool/main/b/btrfs-progs/btrfs-progs_6.14.orig.tar.gz
Link: http://deb.debian.org/debian/pool/main/b/btrfs-progs/btrfs-progs_6.14-1.debian.tar.xz
Cc: xinpeng wang <wangxinpeng@uniontech.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>

diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -6,6 +6,18 @@
 # Temporary array for building the final command, injecting arguments as needed
 declare -a cmd_array
 
+# Check if a given option in config.h is set to 1
+# $1: config option name
+_test_config()
+{
+	local feature="$1"
+
+	if "$TOP/btrfs" --version | grep -q "+${feature}"; then
+		return 0
+	fi
+	return 1
+}
+
 # assert that argument is not empty and is an existing path (file or directory)
 _assert_path()
 {
@@ -220,7 +232,13 @@ run_check()
 	echo "====== RUN CHECK ${cmd_array[@]}" >> "$RESULTS" 2>&1
 	if [[ $TEST_LOG =~ tty ]]; then echo "CMD: ${cmd_array[@]}" > /dev/tty; fi
 
-	"${cmd_array[@]}" >> "$RESULTS" 2>&1 || _fail "failed: ${cmd_array[@]}"
+	"${cmd_array[@]}" >> "$RESULTS" 2>&1
+	if [ "$?" -ne 0 ]; then
+		if echo "${cmd_array[@]}" | grep -q mount; then
+			dmesg | tail -n 15 >> "$RESULTS"
+		fi
+		_fail "failed: ${cmd_array[@]}"
+	fi
 }
 
 # same as run_check but the stderr+stdout output is duplicated on stdout and
@@ -370,6 +388,27 @@ run_mustfail_stdout()
 	fi
 }
 
+check_experimental_build()
+{
+	if ! _test_config "EXPERIMENTAL"; then
+		_not_run "This test requires experimental build"
+	fi
+}
+
+check_regular_build()
+{
+	if _test_config "EXPERIMENTAL"; then
+		_not_run "This test requires non-experimental build"
+	fi
+}
+
+check_injection()
+{
+	if ! _test_config "INJECT"; then
+		_not_run "This test requires error injection support (make D=1)"
+	fi
+}
+
 check_prereq()
 {
 	# Internal tools for testing, not shipped with the package
@@ -395,7 +434,7 @@ check_global_prereq()
 {
 	type -p "$1" &> /dev/null
 	if [ $? -ne 0 ]; then
-		_fail "Failed system wide prerequisities: $1";
+		_fail "Failed system wide prerequisites: $1";
 	fi
 }
 
@@ -441,6 +480,7 @@ check_image()
 
 	image=$1
 	echo "testing image $(basename $image)" >> "$RESULTS"
+	export BTRFS_PROGS_DEBUG_STRICT_CHUNK_ALIGNMENT=y
 	run_mustfail_stdout "btrfs check should have detected corruption"	\
 		"$TOP/btrfs" check "$image" &> "$tmp_output"
 
@@ -449,6 +489,7 @@ check_image()
 
 	run_check "$TOP/btrfs" check --repair --force "$image"
 	run_check_stdout "$TOP/btrfs" check "$image" &> "$tmp_output"
+	unset BTRFS_PROGS_DEBUG_STRICT_CHUNK_ALIGNMENT
 
 	# Also make sure no subpage related warnings for the repaired image
 	check_test_results "$tmp_output" "$testname"
@@ -737,9 +778,9 @@ _get_subvolid()
 DATASET_SIZE=50
 
 generate_dataset() {
+	local dataset_type="$1"
+	local dirpath="$TEST_MNT/$dataset_type"
 
-	dataset_type="$1"
-	dirpath=$TEST_MNT/$dataset_type
 	run_check $SUDO_HELPER mkdir -p "$dirpath"
 
 	case "$dataset_type" in
@@ -841,7 +882,7 @@ setup_loopdevs()
 # create all loop devices from a given loopdev environment
 prepare_loopdevs()
 {
-	for i in `seq $nloopdevs`; do
+	for i in `seq "$nloopdevs"`; do
 		touch "$loopdev_prefix$i"
 		chmod a+rw "$loopdev_prefix$i"
 		truncate -s0 "$loopdev_prefix$i"
@@ -878,6 +919,71 @@ cond_wait_for_loopdevs() {
 	if [ -n "${loopdevs[1]}" ]; then
 		wait_for_loopdevs
 	fi
+}
+
+# Prepare environment for nullb devices, set up the following variables
+# - nullb_count -- number of desired devices
+# - nullb_size -- size of the devices
+# - nullb_zone_size -- zone size of the devices
+# - nullb_devs  -- array containing paths to all devices (after prepare is called)
+#
+# $1: number of nullb devices to be set up
+# $2: size of the devices
+# $3: zone size of the devices
+setup_nullbdevs()
+{
+	if [ "$#" -lt 3 ]; then
+		_fail "setup_nullbdevs <number of device> <size> <zone size>"
+	fi
+
+	setup_root_helper
+	local nullb="$TEST_TOP/nullb"
+
+	run_mayfail $SUDO_HELPER "$nullb" setup
+	if [ $? != 0 ]; then
+		_not_run "cannot setup nullb environment for zoned devices"
+	fi
+
+	nullb_count="$1"
+	nullb_size="$2"
+	nullb_zone_size="$3"
+	declare -a nullb_devs
+}
+
+# Create all nullb devices from a given nullb environment
+prepare_nullbdevs()
+{
+	setup_root_helper
+	local nullb="$TEST_TOP/nullb"
+	local out
+
+	# Record any other pre-existing devices in case creation fails
+	run_check $SUDO_HELPER "$nullb" ls
+
+	for i in `seq "$nullb_count"`; do
+		# Last line has the name of the device node path
+		out=$(run_check_stdout $SUDO_HELPER "$nullb" create -s "$nullb_size" -z "$nullb_zone_size")
+		if [ $? != 0 ]; then
+			_fail "cannot create nullb zoned device $i"
+		fi
+		dev=$(echo "$out" | tail -n 1)
+		nullb_devs[$i]="$dev"
+	done
+
+	run_check $SUDO_HELPER "$nullb" ls
+}
+
+# Remove nullb devices
+cleanup_nullbdevs()
+{
+	setup_root_helper
+	local nullb="$TEST_TOP/nullb"
+	local name
+
+	for dev in ${nullb_devs[@]}; do
+		name=$(basename "$dev")
+		run_check $SUDO_HELPER "$nullb" rm "$name"
+	done
 }
 
 init_env()
